version: '3.8'

services:
  backend:
    build: ./backend
    container_name: cinema-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    networks:
      - cinema-net

  frontend:
    build: ./frontend
    container_name: cinema-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - cinema-net

networks:
  cinema-net:
    driver: bridge